name: Python Unit Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - 'dev'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Install python
        uses: actions/setup-python@v4
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unitary Test
        run: |
          pytest tests/
